### PR TITLE
Adding a setting to define the API base URI

### PR DESCRIPTION
**Pull request by mchojrin**
The idea is to allow changing the URI for testing using a fake server. If the setting is not provided it will default to the real URL

### CODE REVIEW

**Comment by noweh** [comment]
Would it be possible for you to update the README to include this new feature and how to use it? That way, everyone will have the information they need.

Thanks for your contribution!

**Comment by mchojrin** [comment]
Sure! I'll do that :)

**Comment by mchojrin** [comment]
@noweh There you go :)

**Comment by noweh** [comment]
Thanks! :)

**Pull request merged**
